name: tuk_tuk
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_auth: ^4.8.0
  cloud_firestore: ^4.8.0
  firebase_database: ^10.2.0
  cupertino_icons: ^1.0.2
  scoped_model: ^2.0.0
  connectivity_plus: ^2.3.2
  http: ^1.1.0
  google_maps_flutter: ^2.5.3
  geolocator: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/1.jpg
    - assets/images/2.jpg
    - assets/images/tuk.jpg
    - assets/images/login.jpg
    - assets/images/signup.jpg
    - assets/images/log_two.jpg



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
 
